### ISSUE TITLE
1 year = 12 months + 5 days ?

### ISSUE THREAD

**Issue by redDwarf03** [sadespresso/moment_dart#24] opened 2024-08-08 21:05 UTC
## What can be improved?
I have a datetime : DateTime (2025-08-08 22:00:00.000)
I calculate the duration between `now` and a datetime
```DateTime.fromMillisecondsSinceEpoch(farmLockUserInfos.end! * 1000,).difference(DateTime.now().toUtc()).toDurationString()```
The lib returns 12 months and 5 days

## Ideas on implementing the enhancement?
Is it possible to return 12 months ?

Thx

**Comment by sadespresso** [comment] 2024-08-27 06:29
Hello there!

You can try changing the format to month only with `.toDurationString(format: DurationFormat([DurationUnit.month]))`.

If above still doesn't help your use case, please provide enough detail so I can reproduce the issue above. (e.g., replace `now` with ISO 8601 string)

There is something that might be not very well documented about how months are calculated in durations, I will try to document it better.

When calculating durations, months are 30 days, flat. Meaning, `Moment.parse("2025-02-28").difference(Moment.parse("2025-03-31")).toDurationString()` will result in `a month and a day`. 

It's understandable people may expect `a month and 3 days`, but it's unnecessarily complicated, and isn't supported in moment_dart at this time.

**Comment by sadespresso** [comment] 2024-08-27 06:30
Closing this as it seems to be about unsupported feature/function. You can still reply to this thread for more information :D :D

**Closed by sadespresso** 2024-08-27 06:30 UTC
Labels: improvement
